version: "3.9"

services:
  get-tips-200ok-backend:
    container_name: get-tips-200ok-backend
    build:
      context: ./main
    restart: unless-stopped
    ports:
      - "9302:4000"
    env_file:
      - .docker.env
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
